dataset:
  name: "ETTh1"
  csv_path: "data/ETTh1.csv"  # change this
  context_length: 336
  stride: 1

model:
  type: "cnn_ae"
  input_length: 336
  latent_dim: 128cl
  num_channels: 7         # change according to your ETT file

training:
  batch_size: 64        # keep smaller on Mac if you want
  max_epochs: 30
  lr: 1e-3
  weight_decay: 1e-5
  device: "cpu"        # will be resolved by pick_device()

loss:
  use_mse: true
  use_acf: true
  use_periodicity: false
  use_motif: false
  use_freq: true

  lambda_mse: 1.0
  lambda_acf: 0.5       # stronger than before, ACF behaves nicely
  lambda_periodicity: 0.0
  lambda_motif: 0.0
  lambda_freq: 0.01     # much weaker freq, now a gentle regularizer

  acf:
    max_lag: 48
    periodic_lags: [24, 48]

  freq:
    use_full_spectrum: true
    max_bins: null
    use_log: true
    normalize: true

logging:
  log_every_n_steps: 50
  ckpt_dir: "checkpoints/ett_tpc_minimal"
